alias dir='ls --color=auto --format=vertical -la'
export HISTSIZE=10000 HISTFILESIZE=100000
export JAVA_HOME=/usr/java/jdk-23
export PATH=$PATH:$JAVA_HOME/bin

export SIGMA_HOME=/home/sumo/.sigmakee
export ONTOLOGYPORTAL_GIT=/home/sumo/workspace
export CATALINA_HOME=/home/sumo/Programs/apache-tomcat-9.0.96
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

# Additional stuff for sigmanlp
export SIGMA_SRC=/home/sumo/workspace/sigmakee
export CATALINA_OPTS="$CATALINA_OPTS -Xss1m -Xmx10g"
