package com.articulate.nlp.morphodb;

import com.articulate.nlp.GenUtils;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.io.File;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/***************************************************************
 * Read-only interface over a morphology DB snapshot generated by
 * GenMorphoDB.
 ***************************************************************/
public class MorphoDB {

    public static class ModelMorphoDB {
        public final String modelDirectory;
        public final NounMorphoDB nouns;
        public final VerbMorphoDB verbs;
        public final AdjectiveMorphoDB adjectives;
        public final AdverbMorphoDB adverbs;
        public final PrepositionMorphoDB prepositions;

        public ModelMorphoDB(String modelDirectory,
                             NounMorphoDB nouns,
                             VerbMorphoDB verbs,
                             AdjectiveMorphoDB adjectives,
                             AdverbMorphoDB adverbs,
                             PrepositionMorphoDB prepositions) {
            this.modelDirectory = modelDirectory;
            this.nouns = nouns;
            this.verbs = verbs;
            this.adjectives = adjectives;
            this.adverbs = adverbs;
            this.prepositions = prepositions;
        }
    }

    public final Map<String, ModelMorphoDB> byModel = new LinkedHashMap<>();

    // --- LLM query-on-miss configuration ---
    private boolean           queryMissingWords = false;
    private String            llmModel          = null;
    private String            dbRootPath        = null;
    private final Set<String>         queriedNouns   = new HashSet<>();
    private final Map<String, String> cachedPlurals  = new HashMap<>();
    private final Map<String, String> cachedArticles = new HashMap<>();
    private final Set<String> cachedNounErrorLemmas = new HashSet<>();
    private boolean nounErrorCacheLoaded = false;

    private final Set<String> queriedVerbs = new HashSet<>();
    // lemmaKey → tenseKey → personKey → surface form
    private final Map<String, Map<String, Map<String, String>>> cachedVerbConjugations = new HashMap<>();
    private final Set<String> cachedVerbErrorLemmas = new HashSet<>();

    public static MorphoDB loadMorphoDatabase(String morphoDbPath,
                                              boolean queryMissingWords,
                                              String  llmModel) {
        MorphoDB db = new MorphoDB();
        db.queryMissingWords = queryMissingWords;
        db.llmModel          = llmModel;
        Path resolvedPath = GenMorphoUtils.expandHomePath(morphoDbPath);
        File root = resolvedPath.toFile();
        if (!root.exists() || !root.isDirectory()) {
            return db;
        }
        db.dbRootPath = root.getAbsolutePath();
        String modelDirectory = root.getName();
        ModelMorphoDB modelDB = new ModelMorphoDB(
                modelDirectory,
                NounMorphoDB.load(root.getPath()),
                VerbMorphoDB.load(root.getPath()),
                AdjectiveMorphoDB.load(root.getPath()),
                AdverbMorphoDB.load(root.getPath()),
                PrepositionMorphoDB.load(root.getPath()));
        db.byModel.put(modelDirectory, modelDB);
        return db;
    }

    public static MorphoDB loadMorphoDatabase(String morphoDbPath) {
        return loadMorphoDatabase(morphoDbPath, false, null);
    }

    /***************************************************************
     * Queries the configured LLM for plural and indefinite article of
     * the given noun. Results are cached in memory and persisted to the
     * DB files. Uses cheap-prompt mode to minimise token usage.
     * No-ops if the noun has already been queried this session.
     ***************************************************************/
    private void queryAndCacheNoun(String noun, String sumoTerm) {
        String key = GenMorphoUtils.normalizeLemma(noun);
        if (key.isEmpty()) return;
        if (queriedNouns.contains(key)) return;
        queriedNouns.add(key);
        String model = (llmModel != null && !llmModel.isEmpty()) ? llmModel : GenUtils.getLLMModel();
        if (llmModel != null && !llmModel.isEmpty())
            GenUtils.setLLMModel(llmModel);
        System.out.println("Querying " + model + " for morphological information about '" + noun + "'.");
        String basePrompt =
                "Provide English morphological information for the noun \"" + noun + "\" " +
                "as a JSON object with fields: singular, plural, article (\"a\" or \"an\").";
        boolean prevCheap = GenUtils.isCheapPromptMode();
        GenUtils.setCheapPromptMode(true);
        String prompt = GenMorphoUtils.applyCheapPromptDirective(
                basePrompt, List.of("singular", "plural", "article"));
        try {
            String response = GenUtils.askLLM(prompt);
            ObjectNode node = GenMorphoUtils.extractRequiredJsonObject(
                    response, List.of("plural", "article"));
            if (node == null) {
                persistNounErrorEntry(key, model, sumoTerm, response,
                        "Unable to parse noun morphology response.");
                return;
            }
            String plural  = node.path("plural").asText("").trim();
            String article = node.path("article").asText("").trim().toLowerCase();
            boolean hasPlural = !plural.isEmpty();
            boolean hasArticle = "a".equals(article) || "an".equals(article);
            if (hasPlural) cachedPlurals.put(key, plural);
            if (hasArticle) cachedArticles.put(key, article);
            if (!hasPlural && !hasArticle) {
                persistNounErrorEntry(key, model, sumoTerm, response,
                        "LLM response missing usable plural/article values.");
                return;
            }
            persistNounEntry(key, plural, article, model, sumoTerm);
        } catch (Exception e) {
            System.out.println("MorphoDB: LLM query failed for '" + noun + "': " + e.getMessage());
            persistNounErrorEntry(key, model, sumoTerm, null,
                    "LLM query failed: " + e.getMessage());
        } finally {
            GenUtils.setCheapPromptMode(prevCheap);
        }
    }

    /***************************************************************
     * Appends plural and/or article JSON records to the existing DB
     * files, each with a fresh SUMO_XXXXXX synset ID.
     ***************************************************************/
    private void persistNounEntry(String singular, String plural, String article, String model, String sumoTerm) {
        if (dbRootPath == null) return;
        String synsetId = (sumoTerm != null && !sumoTerm.trim().isEmpty()) ? sumoTerm.trim() : "LLM-generated";
        String dbName = new java.io.File(dbRootPath).getName();
        if (!plural.isEmpty()) {
            ObjectNode rec = GenMorphoUtils.JSON_MAPPER.createObjectNode()
                    .put("synsetId", synsetId).put("lemma", singular).put("singular", singular)
                    .put("plural", plural).put("type", "count noun").put("explanation", "LLM-generated")
                    .put("plural_pattern", "Unknown");
            GenMorphoUtils.appendJsonLine(dbRootPath + "/noun/Plurals.txt", rec);
            System.out.println("Successfully received response from " + model
                    + ". Adding plural '" + plural + "' for '" + singular + "' to " + dbName + "/noun/Plurals.txt.");
        }
        if ("a".equals(article) || "an".equals(article)) {
            ObjectNode rec = GenMorphoUtils.JSON_MAPPER.createObjectNode()
                    .put("synsetId", synsetId).put("lemma", singular).put("noun", singular)
                    .put("article", article).put("explanation", "LLM-generated");
            GenMorphoUtils.appendJsonLine(dbRootPath + "/noun/IndefiniteArticles.txt", rec);
            System.out.println("Successfully received response from " + model
                    + ". Adding article '" + article + "' for '" + singular + "' to " + dbName + "/noun/IndefiniteArticles.txt.");
        }
    }

    /***************************************************************
     * Persists error markers so failed LLM noun lookups do not keep
     * retriggering indefinitely across runs.
     ***************************************************************/
    private void persistNounErrorEntry(String singular,
                                       String model,
                                       String sumoTerm,
                                       String llmResponse,
                                       String errorMessage) {

        if (dbRootPath == null || singular == null || singular.trim().isEmpty()) {
            return;
        }
        String normalizedLemma = GenMorphoUtils.normalizeLemma(singular);
        if (normalizedLemma.isEmpty()) {
            return;
        }
        String synsetId = (sumoTerm != null && !sumoTerm.trim().isEmpty()) ? sumoTerm.trim() : "LLM-generated";
        String dbName = new java.io.File(dbRootPath).getName();

        String pluralErrorLine = GenMorphoUtils.buildErrorRecord(
                "singular",
                normalizedLemma,
                normalizedLemma,
                synsetId,
                "",
                llmResponse,
                errorMessage == null ? "Unable to classify noun plural." : errorMessage);
        ObjectNode pluralErrorNode = GenMorphoUtils.parseJsonObjectLine(pluralErrorLine);
        if (pluralErrorNode != null) {
            GenMorphoUtils.appendJsonLine(dbRootPath + "/noun/Plurals.txt", pluralErrorNode);
        }

        String articleErrorLine = GenMorphoUtils.buildErrorRecord(
                "noun",
                normalizedLemma,
                normalizedLemma,
                synsetId,
                "",
                llmResponse,
                errorMessage == null ? "Unable to classify noun article." : errorMessage);
        ObjectNode articleErrorNode = GenMorphoUtils.parseJsonObjectLine(articleErrorLine);
        if (articleErrorNode != null) {
            GenMorphoUtils.appendJsonLine(dbRootPath + "/noun/IndefiniteArticles.txt", articleErrorNode);
        }
        cachedNounErrorLemmas.add(normalizedLemma);

        System.out.println("Persisted noun error marker for '" + normalizedLemma + "' to " + dbName + "/noun/{Plurals,IndefiniteArticles}.txt");
    }

    private boolean hasPersistedNounError(String noun) {

        String key = GenMorphoUtils.normalizeLemma(noun);
        if (key.isEmpty()) {
            return false;
        }
        if (!nounErrorCacheLoaded) {
            loadNounErrorCache();
        }
        return cachedNounErrorLemmas.contains(key);
    }

    private void loadNounErrorCache() {

        if (nounErrorCacheLoaded) {
            return;
        }
        for (ModelMorphoDB model : byModel.values()) {
            cacheNounErrorLemmas(model.nouns.plurals, "singular");
            cacheNounErrorLemmas(model.nouns.indefiniteArticles, "noun");
        }
        nounErrorCacheLoaded = true;
    }

    private void cacheNounErrorLemmas(Map<String, List<ObjectNode>> recordsByKey,
                                      String fallbackFieldName) {

        if (recordsByKey == null || recordsByKey.isEmpty()) {
            return;
        }
        for (List<ObjectNode> rows : recordsByKey.values()) {
            if (rows == null) continue;
            for (ObjectNode row : rows) {
                if (row == null) continue;
                if (!"error".equalsIgnoreCase(row.path("status").asText(""))) continue;
                String lemma = GenMorphoUtils.normalizeLemma(row.path("lemma").asText(""));
                if (lemma.isEmpty()) {
                    lemma = GenMorphoUtils.normalizeLemma(row.path(fallbackFieldName).asText(""));
                }
                if (!lemma.isEmpty()) {
                    cachedNounErrorLemmas.add(lemma);
                }
            }
        }
    }

    public int size() {
        return byModel.size();
    }

    /***************************************************************
     * Lookup verb conjugation across all loaded models in iteration order.
     * Queries the LLM on miss if queryMissingWords is enabled, persisting
     * the result to verb/VerbConjugations.txt for future runs.
     ***************************************************************/
    public String getVerbConjugation(String lemma, String tense, String grammaticalPerson) {

        for (ModelMorphoDB model : byModel.values()) {
            String value = model.verbs.getVerbConjugation(lemma, tense, grammaticalPerson);
            if (value != null && !value.trim().isEmpty()) {
                return value;
            }
        }
        String cached = getCachedVerbConjugation(lemma, tense, grammaticalPerson);
        if (cached != null) {
            return cached;
        }
        if (queryMissingWords && lemma != null && !lemma.trim().isEmpty()) {
            String key = GenMorphoUtils.normalizeLemma(lemma);
            if (!cachedVerbErrorLemmas.contains(key)) {
                queryAndCacheVerb(lemma.trim());
                return getCachedVerbConjugation(lemma, tense, grammaticalPerson);
            }
        }
        return null;
    }

    private String getCachedVerbConjugation(String lemma, String tense, String person) {

        if (lemma == null || tense == null || person == null) {
            return null;
        }
        Map<String, Map<String, String>> byTense = cachedVerbConjugations
                .get(GenMorphoUtils.normalizeLemma(lemma));
        if (byTense == null) {
            return null;
        }
        Map<String, String> byPerson = byTense.get(tense.trim().toLowerCase());
        if (byPerson == null) {
            return null;
        }
        return byPerson.get(person.trim().toLowerCase());
    }

    private void queryAndCacheVerb(String lemma) {

        String key = GenMorphoUtils.normalizeLemma(lemma);
        if (key.isEmpty() || queriedVerbs.contains(key)) {
            return;
        }
        queriedVerbs.add(key);
        String model = (llmModel != null && !llmModel.isEmpty()) ? llmModel : GenUtils.getLLMModel();
        if (llmModel != null && !llmModel.isEmpty()) {
            GenUtils.setLLMModel(llmModel);
        }
        System.out.println("Querying " + model + " for verb conjugations of '" + lemma + "'.");
        ObjectNode record = VerbConjugationUtils.queryAndCanonicalizeConjugation(lemma, "LLM-generated", "");
        if (record == null) {
            cachedVerbErrorLemmas.add(key);
            persistVerbErrorEntry(lemma, "Unable to parse verb conjugation response.");
            System.out.println("MorphoDB: LLM query failed or returned unparseable response for verb '" + lemma + "'.");
            return;
        }
        // Populate in-memory cache from the tenses array
        JsonNode tensesNode = record.get("tenses");
        if (tensesNode != null && tensesNode.isArray()) {
            for (JsonNode tenseNode : tensesNode) {
                String tenseKey = tenseNode.path("tense").asText("").trim().toLowerCase();
                if (tenseKey.isEmpty()) {
                    continue;
                }
                JsonNode forms = tenseNode.get("forms");
                if (forms == null) {
                    continue;
                }
                Map<String, String> personMap = cachedVerbConjugations
                        .computeIfAbsent(key, k -> new HashMap<>())
                        .computeIfAbsent(tenseKey, k -> new HashMap<>());
                for (String person : List.of("i", "you_singular", "he_she_it", "we", "you_plural", "they")) {
                    String rawForm = forms.path(person).asText("").trim();
                    String form = VerbConjugationUtils.normalizeVerbFormForIndex(rawForm, key, person);
                    if (form != null && !form.isEmpty()) {
                        personMap.putIfAbsent(person, form);
                    }
                }
            }
        }
        // Persist to disk
        if (dbRootPath != null) {
            String dbName = new File(dbRootPath).getName();
            GenMorphoUtils.appendJsonLine(dbRootPath + "/verb/VerbConjugations.txt", record);
            System.out.println("Added conjugations for '" + lemma + "' to " + dbName + "/verb/VerbConjugations.txt.");
        }
    }

    private void persistVerbErrorEntry(String lemma, String errorMessage) {

        if (dbRootPath == null || lemma == null || lemma.trim().isEmpty()) {
            return;
        }
        String key = GenMorphoUtils.normalizeLemma(lemma);
        if (key.isEmpty()) {
            return;
        }
        String errorLine = GenMorphoUtils.buildErrorRecord(
                "verb", lemma, key, "LLM-generated", "", null,
                errorMessage == null ? "Unable to classify verb conjugation." : errorMessage);
        ObjectNode errorNode = GenMorphoUtils.parseJsonObjectLine(errorLine);
        if (errorNode != null) {
            GenMorphoUtils.appendJsonLine(dbRootPath + "/verb/VerbConjugations.txt", errorNode);
        }
    }

    /***************************************************************
     * Returns the dependent preposition for the given positional
     * surface form (e.g. "adjacent" → "to", "downstream" → "from",
     * "on" → "").  Returns null if the term is not recognised.
     ***************************************************************/
    public String getPositionalPreposition(String surfaceForm) {

        for (ModelMorphoDB model : byModel.values()) {
            String prep = model.prepositions.getPositionalPreposition(surfaceForm);
            if (prep != null) {
                return prep;
            }
        }
        return null;
    }

    /***************************************************************
     * Returns "the" if this positional term needs a definite article
     * when used after a frame-supplied preposition (e.g. "from the
     * north"), or "" if no article is needed (e.g. "from upstream").
     ***************************************************************/
    public String getPositionalArticle(String surfaceForm) {

        for (ModelMorphoDB model : byModel.values()) {
            String article = model.prepositions.getPositionalArticle(surfaceForm);
            if (article != null && !article.isEmpty()) {
                return article;
            }
        }
        return "";
    }

    /***************************************************************
     * Returns "a" or "an" for the given noun. Queries the LLM on miss
     * if queryMissingWords is enabled, using sumoTerm as the synsetId
     * for the persisted record.
     ***************************************************************/
    public String getIndefiniteArticle(String noun, String sumoTerm) {

        for (ModelMorphoDB model : byModel.values()) {
            String article = model.nouns.getIndefiniteArticle(noun);
            if (article != null) {
                return article;
            }
        }
        if (noun != null) {
            String trimmed = noun.trim();
            int firstSpace = trimmed.indexOf(' ');
            if (firstSpace >= 0) {
                String firstWord = trimmed.substring(0, firstSpace);
                for (ModelMorphoDB model : byModel.values()) {
                    String firstWordArticle = model.nouns.getIndefiniteArticle(firstWord);
                    if (firstWordArticle != null) {
                        return firstWordArticle;
                    }
                }
            }
        }
        System.out.println("Warning: noun '" + noun + "' not found in any model; using default article heuristic.");
        if (queryMissingWords && noun != null && !noun.trim().isEmpty()) {
            if (hasPersistedNounError(noun)) {
                System.out.println("Skipping LLM query for article of '" + noun + "' due to persisted error marker.");
            } else {
                queryAndCacheNoun(noun.trim(), sumoTerm);
                String cached = cachedArticles.get(GenMorphoUtils.normalizeLemma(noun));
                if (cached != null) return cached;
                System.out.println("Query unsuccessful for article of '" + noun + "'. Using heuristic fallback.");
            }
        }
        return defaultIndefiniteArticle(noun);
    }

    /***************************************************************
     * Returns "a" or "an" for the given noun. Never queries the LLM.
     ***************************************************************/
    public String getIndefiniteArticle(String noun) {

        for (ModelMorphoDB model : byModel.values()) {
            String article = model.nouns.getIndefiniteArticle(noun);
            if (article != null) {
                return article;
            }
        }
        if (noun != null) {
            String trimmed = noun.trim();
            int firstSpace = trimmed.indexOf(' ');
            if (firstSpace >= 0) {
                String firstWord = trimmed.substring(0, firstSpace);
                for (ModelMorphoDB model : byModel.values()) {
                    String firstWordArticle = model.nouns.getIndefiniteArticle(firstWord);
                    if (firstWordArticle != null) {
                        return firstWordArticle;
                    }
                }
            }
        }
        return defaultIndefiniteArticle(noun);
    }

    /***************************************************************
     * Fallback indefinite article using the first letter of the noun.
     * Words beginning with a vowel letter get "an"; all others get "a".
     ***************************************************************/
    private static String defaultIndefiniteArticle(String noun) {

        if (noun == null || noun.trim().isEmpty()) {
            return "a";
        }
        char first = Character.toLowerCase(noun.trim().charAt(0));
        return "aeiou".indexOf(first) >= 0 ? "an" : "a";
    }

    /***************************************************************
     * Returns the plural form for the given noun. Queries the LLM on
     * miss if queryMissingWords is enabled, using sumoTerm as the
     * synsetId for the persisted record.
     ***************************************************************/
    public String getPlural(String noun, String sumoTerm) {

        for (ModelMorphoDB model : byModel.values()) {
            String plural = model.nouns.getPlural(noun);
            if (plural != null) {
                return plural;
            }
        }
        if (noun != null) {
            String trimmed = noun.trim();
            int lastSpace = trimmed.lastIndexOf(' ');
            if (lastSpace >= 0) {
                String lastWord = trimmed.substring(lastSpace + 1);
                String prefix = trimmed.substring(0, lastSpace + 1);
                for (ModelMorphoDB model : byModel.values()) {
                    String lastWordPlural = model.nouns.getPlural(lastWord);
                    if (lastWordPlural != null) {
                        return prefix + lastWordPlural;
                    }
                }
            }
        }
        System.out.println("Warning: plural for '" + noun + "' not found in MorphoDB; using suffix fallback.");
        if (queryMissingWords && noun != null && !noun.trim().isEmpty()) {
            if (hasPersistedNounError(noun)) {
                System.out.println("Skipping LLM query for plural of '" + noun + "' due to persisted error marker.");
            } else {
                queryAndCacheNoun(noun.trim(), sumoTerm);
                String cached = cachedPlurals.get(GenMorphoUtils.normalizeLemma(noun));
                if (cached != null) return cached;
                System.out.println("Query unsuccessful for plural of '" + noun + "'. Using suffix fallback.");
            }
        }
        return defaultPlural(noun);
    }

    /***************************************************************
     * Returns the plural form for the given noun. Never queries the LLM.
     ***************************************************************/
    public String getPlural(String noun) {

        for (ModelMorphoDB model : byModel.values()) {
            String plural = model.nouns.getPlural(noun);
            if (plural != null) {
                return plural;
            }
        }
        if (noun != null) {
            String trimmed = noun.trim();
            int lastSpace = trimmed.lastIndexOf(' ');
            if (lastSpace >= 0) {
                String lastWord = trimmed.substring(lastSpace + 1);
                String prefix = trimmed.substring(0, lastSpace + 1);
                for (ModelMorphoDB model : byModel.values()) {
                    String lastWordPlural = model.nouns.getPlural(lastWord);
                    if (lastWordPlural != null) {
                        return prefix + lastWordPlural;
                    }
                }
            }
        }
        return defaultPlural(noun);
    }

    /***************************************************************
     * Fallback plural using standard English suffix rules.
     * Prints a warning so missing nouns can be added to the MorphoDB.
     ***************************************************************/
    private static String defaultPlural(String noun) {

        if (noun == null || noun.trim().isEmpty()) {
            return noun;
        }
        String n = noun.trim();
        String lower = n.toLowerCase();
        if (lower.endsWith("ch") || lower.endsWith("sh") || lower.endsWith("s")
                || lower.endsWith("x") || lower.endsWith("z")) {
            return n + "es";
        }
        if (lower.length() > 1 && lower.endsWith("y")
                && "aeiou".indexOf(lower.charAt(lower.length() - 2)) < 0) {
            return n.substring(0, n.length() - 1) + "ies";
        }
        return n + "s";
    }

}
