package com.articulate.nlp.morphodb;

import java.io.File;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

/***************************************************************
 * Read-only interface over a morphology DB snapshot generated by
 * GenMorphoDB.
 ***************************************************************/
public class MorphoDB {

    public static class ModelMorphoDB {
        public final String modelDirectory;
        public final NounMorphoDB nouns;
        public final VerbMorphoDB verbs;
        public final AdjectiveMorphoDB adjectives;
        public final AdverbMorphoDB adverbs;

        public ModelMorphoDB(String modelDirectory,
                             NounMorphoDB nouns,
                             VerbMorphoDB verbs,
                             AdjectiveMorphoDB adjectives,
                             AdverbMorphoDB adverbs) {
            this.modelDirectory = modelDirectory;
            this.nouns = nouns;
            this.verbs = verbs;
            this.adjectives = adjectives;
            this.adverbs = adverbs;
        }
    }

    public final Map<String, ModelMorphoDB> byModel = new LinkedHashMap<>();

    public static MorphoDB loadMorphoDatabase(String morphoDbPath) {

        MorphoDB db = new MorphoDB();
        Path resolvedPath = GenMorphoUtils.expandHomePath(morphoDbPath);
        File root = resolvedPath.toFile();
        if (!root.exists() || !root.isDirectory()) {
            return db;
        }
        String modelDirectory = root.getName();
        ModelMorphoDB modelDB = new ModelMorphoDB(
                modelDirectory,
                NounMorphoDB.load(root.getPath()),
                VerbMorphoDB.load(root.getPath()),
                AdjectiveMorphoDB.load(root.getPath()),
                AdverbMorphoDB.load(root.getPath()));
        db.byModel.put(modelDirectory, modelDB);
        return db;
    }

    public int size() {
        return byModel.size();
    }

    /***************************************************************
     * Lookup verb conjugation across all loaded models in iteration order.
     ***************************************************************/
    public String getVerbConjugation(String lemma, String tense, String grammaticalPerson) {

        for (ModelMorphoDB model : byModel.values()) {
            String value = model.verbs.getVerbConjugation(lemma, tense, grammaticalPerson);
            if (value != null && !value.trim().isEmpty()) {
                return value;
            }
        }
        return null;
    }

    /***************************************************************
     * Returns "a" or "an" for the given noun surface string.
     * Checks all loaded models in iteration order; if the noun is
     * not found in any model, falls back to a letter-based heuristic.
     ***************************************************************/
    public String getIndefiniteArticle(String noun) {

        for (ModelMorphoDB model : byModel.values()) {
            String article = model.nouns.getIndefiniteArticle(noun);
            if (article != null) {
                return article;
            }
        }
        return defaultIndefiniteArticle(noun);
    }

    /***************************************************************
     * Fallback indefinite article using the first letter of the noun.
     * Words beginning with a vowel letter get "an"; all others get "a".
     ***************************************************************/
    private static String defaultIndefiniteArticle(String noun) {

        if (noun == null || noun.trim().isEmpty()) {
            return "a";
        }
        char first = Character.toLowerCase(noun.trim().charAt(0));
        return "aeiou".indexOf(first) >= 0 ? "an" : "a";
    }

}
