package com.articulate.nlp.morphodb;

import com.fasterxml.jackson.databind.node.ObjectNode;

import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/***************************************************************
 * Read-only preposition database.
 *
 * Currently handles dependent prepositions for SUMO
 * PositionalAttribute terms: maps the English surface form to
 * the connecting preposition (if any) required after it when
 * used predicatively.  An empty string means no connecting word
 * is needed.
 *
 * Examples:
 *   "adjacent"   → "to"    ("adjacent to the chair")
 *   "downstream" → "from"  ("downstream from the bridge")
 *   "north"      → "of"    ("north of the city")
 *   "on"         → ""      ("on the chair")
 *
 * Currently backed by a hardcoded table (Option B).  When
 * positional/PositionalPrepositions.txt is generated by the LLM
 * pipeline (Option C), load() will prefer the file and fall back
 * to the hardcoded table for any surface form not found there.
 ***************************************************************/
public class PrepositionMorphoDB {

    /***************************************************************
     * Hardcoded fallback table: lowercase surface form → dependent
     * preposition.  Covers common SUMO PositionalAttribute instances.
     ***************************************************************/
    private static final Map<String, String> HARDCODED;
    static {
        Map<String, String> m = new HashMap<>();
        // True prepositions — no connecting word needed
        m.put("on",          "");
        m.put("above",       "");
        m.put("below",       "");
        m.put("under",       "");
        m.put("over",        "");
        m.put("behind",      "");
        m.put("beside",      "");
        m.put("between",     "");
        m.put("near",        "");
        m.put("inside",      "");
        m.put("outside",     "");
        m.put("around",      "");
        m.put("along",       "");
        m.put("across",      "");
        m.put("through",     "");
        m.put("within",      "");
        m.put("beneath",     "");
        m.put("atop",        "");
        m.put("amid",        "");
        m.put("by",          "");
        m.put("past",        "");
        m.put("beyond",      "");
        m.put("horizontal",  "");  // intrinsic orientation; no reference object needed
        m.put("vertical",    "");  // intrinsic orientation; no reference object needed
        // Adjectives requiring "to"
        m.put("next",        "to");
        m.put("adjacent",    "to");
        m.put("close",       "to");
        m.put("opposite",    "to");
        m.put("prior",       "to");
        m.put("right angle", "to");  // at a right angle to
        // Adverbs/adjectives requiring "from"
        m.put("downstream", "from");
        m.put("upstream",   "from");
        m.put("downhill",   "from");
        m.put("uphill",     "from");
        m.put("clockwise",  "from");
        m.put("far",        "from");
        m.put("away",       "from");
        m.put("apart",      "from");
        // Requiring "of"
        m.put("north",      "of");
        m.put("south",      "of");
        m.put("east",       "of");
        m.put("west",       "of");
        m.put("northeast",  "of");
        m.put("northwest",  "of");
        m.put("southeast",  "of");
        m.put("southwest",  "of");
        m.put("ahead",      "of");
        m.put("in front",   "of");
        m.put("right",      "of");
        m.put("left",       "of");
        m.put("upwind",     "of");
        // Requiring "by"
        m.put("surrounded", "by");  // surrounded by
        HARDCODED = m;
    }

    /***************************************************************
     * Hardcoded article table: terms that need "the" when used as a
     * bare source/direction after a frame-supplied preposition.
     * e.g. "from the north" (cardinal), "from the left" (body-relative).
     * Directional adverbs (upstream, uphill) and true prepositions
     * (on, above) are absent — they take no article.
     ***************************************************************/
    private static final Map<String, String> HARDCODED_ARTICLE;
    static {
        Map<String, String> a = new HashMap<>();
        // Cardinal directions — used as nouns: "from the north"
        a.put("north",      "the");
        a.put("south",      "the");
        a.put("east",       "the");
        a.put("west",       "the");
        a.put("northeast",  "the");
        a.put("northwest",  "the");
        a.put("southeast",  "the");
        a.put("southwest",  "the");
        // Body-relative nouns — "from the left", "from the right", "from the front"
        a.put("left",       "the");
        a.put("right",      "the");
        a.put("in front",   "the");
        HARDCODED_ARTICLE = a;
    }

    // Primary lookup: built from either the loaded file or the hardcoded table.
    private final Map<String, String> prepBySurface;
    private final Map<String, String> articleBySurface;

    private PrepositionMorphoDB(Map<String, String> prepBySurface,
                                Map<String, String> articleBySurface) {
        this.prepBySurface    = prepBySurface;
        this.articleBySurface = articleBySurface;
    }

    /***************************************************************
     * Loads preposition data for the given model directory.
     * Hardcoded tables are used as the base; if
     * positional/PositionalPrepositions.txt exists its entries
     * overlay the hardcoded values (Option C).
     ***************************************************************/
    public static PrepositionMorphoDB load(String morphoDbPath) {

        Map<String, String> preps    = new HashMap<>(HARDCODED);
        Map<String, String> articles = new HashMap<>(HARDCODED_ARTICLE);
        Path file = GenMorphoUtils.expandHomePath(morphoDbPath)
                .resolve("positional").resolve("PositionalPrepositions.txt");
        if (file.toFile().exists()) {
            Map<String, List<ObjectNode>> loaded =
                    GenMorphoUtils.loadClassificationObjects(file.toString());
            for (List<ObjectNode> records : loaded.values()) {
                if (records == null) continue;
                for (ObjectNode rec : records) {
                    String surface = rec.path("surface_form").asText("").trim().toLowerCase();
                    if (surface.isEmpty()) continue;
                    if (rec.has("preposition")) preps.put(surface, rec.path("preposition").asText(""));
                    if (rec.has("article"))     articles.put(surface, rec.path("article").asText(""));
                }
            }
        }
        return new PrepositionMorphoDB(preps, articles);
    }

    /***************************************************************
     * Returns the dependent preposition for the given positional
     * surface form (case-insensitive), or null if the term is not
     * recognised.  An empty string means no connecting word is needed.
     ***************************************************************/
    public String getPositionalPreposition(String surfaceForm) {

        if (surfaceForm == null || surfaceForm.isEmpty()) {
            return null;
        }
        return prepBySurface.get(surfaceForm.trim().toLowerCase());
    }

    /***************************************************************
     * Returns "the" if this positional term needs a definite article
     * when used as a bare source/direction after a frame-supplied
     * preposition (e.g. "from the north"), or "" if no article is
     * needed (e.g. "from upstream").  Returns "" for unknown terms.
     ***************************************************************/
    public String getPositionalArticle(String surfaceForm) {

        if (surfaceForm == null || surfaceForm.isEmpty()) {
            return "";
        }
        String article = articleBySurface.get(surfaceForm.trim().toLowerCase());
        return article != null ? article : "";
    }
}
