package com.articulate.nlp.morphodb;

import java.util.HashMap;
import java.util.Map;

/***************************************************************
 * Read-only preposition database.
 *
 * Currently handles dependent prepositions for SUMO
 * PositionalAttribute terms: maps the English surface form to
 * the connecting preposition (if any) required after it when
 * used predicatively.  An empty string means no connecting word
 * is needed.
 *
 * Examples:
 *   "adjacent"   → "to"    ("adjacent to the chair")
 *   "downstream" → "from"  ("downstream from the bridge")
 *   "north"      → "of"    ("north of the city")
 *   "on"         → ""      ("on the chair")
 *
 * Currently backed by a hardcoded table (Option B).  When
 * positional/PositionalPrepositions.txt is generated by the LLM
 * pipeline (Option C), load() will prefer the file and fall back
 * to the hardcoded table for any surface form not found there.
 ***************************************************************/
public class PrepositionMorphoDB {

    /***************************************************************
     * Hardcoded fallback table: lowercase surface form → dependent
     * preposition.  Covers common SUMO PositionalAttribute instances.
     ***************************************************************/
    private static final Map<String, String> HARDCODED;
    static {
        Map<String, String> m = new HashMap<>();
        // True prepositions — no connecting word needed
        m.put("on",          "");
        m.put("above",       "");
        m.put("below",       "");
        m.put("under",       "");
        m.put("over",        "");
        m.put("behind",      "");
        m.put("beside",      "");
        m.put("between",     "");
        m.put("near",        "");
        m.put("inside",      "");
        m.put("outside",     "");
        m.put("around",      "");
        m.put("along",       "");
        m.put("across",      "");
        m.put("through",     "");
        m.put("within",      "");
        m.put("beneath",     "");
        m.put("atop",        "");
        m.put("amid",        "");
        m.put("by",          "");
        m.put("past",        "");
        m.put("beyond",      "");
        m.put("horizontal",  "");  // intrinsic orientation; no reference object needed
        m.put("vertical",    "");  // intrinsic orientation; no reference object needed
        // Adjectives requiring "to"
        m.put("next",        "to");
        m.put("adjacent",    "to");
        m.put("close",       "to");
        m.put("opposite",    "to");
        m.put("prior",       "to");
        m.put("right angle", "to");  // at a right angle to
        // Adverbs/adjectives requiring "from"
        m.put("downstream", "from");
        m.put("upstream",   "from");
        m.put("downhill",   "from");
        m.put("uphill",     "from");
        m.put("clockwise",  "from");
        m.put("far",        "from");
        m.put("away",       "from");
        m.put("apart",      "from");
        // Requiring "of"
        m.put("north",      "of");
        m.put("south",      "of");
        m.put("east",       "of");
        m.put("west",       "of");
        m.put("northeast",  "of");
        m.put("northwest",  "of");
        m.put("southeast",  "of");
        m.put("southwest",  "of");
        m.put("ahead",      "of");
        m.put("in front",   "of");
        m.put("right",      "of");
        m.put("left",       "of");
        m.put("upwind",     "of");
        // Requiring "by"
        m.put("surrounded", "by");  // surrounded by
        HARDCODED = m;
    }

    // Primary lookup: built from either the loaded file or the hardcoded table.
    private final Map<String, String> prepBySurface;

    private PrepositionMorphoDB(Map<String, String> prepBySurface) {
        this.prepBySurface = prepBySurface;
    }

    /***************************************************************
     * Loads preposition data for the given model directory.
     * Option C: when positional/PositionalPrepositions.txt exists, its
     * entries are loaded first and the hardcoded table fills any gaps.
     * Until that file is generated, the hardcoded table is used directly.
     ***************************************************************/
    public static PrepositionMorphoDB load(String morphoDbPath) {

        // Option C: when positional/PositionalPrepositions.txt is generated by
        // the LLM pipeline, load it here and merge with HARDCODED as fallback.
        return new PrepositionMorphoDB(new HashMap<>(HARDCODED));
    }

    /***************************************************************
     * Returns the dependent preposition for the given positional
     * surface form (case-insensitive), or null if the term is not
     * recognised.  An empty string means no connecting word is needed.
     ***************************************************************/
    public String getPositionalPreposition(String surfaceForm) {

        if (surfaceForm == null || surfaceForm.isEmpty()) {
            return null;
        }
        return prepBySurface.get(surfaceForm.trim().toLowerCase());
    }
}
