package com.articulate.nlp;

import io.github.ollama4j.OllamaAPI;
import io.github.ollama4j.models.response.OllamaResult;
import io.github.ollama4j.types.OllamaModelType;
import io.github.ollama4j.utils.OptionsBuilder;
import io.github.ollama4j.utils.Options;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/** Relation phrases are often times awkwardly formed.
 * This code takes in a file of generated relations and
 * re-phrases them less awkwardly.
 */
public class RephraseRelationsTestData {

    public static boolean RAW_PROMPT = false;
    public static Options options;

    public static void main(String[] args) throws Exception {
        System.out.println("Starting relation test data rephraser.");

        if (args.length != 3) {
            System.out.println("Usage: RephraseRelationsTestData <input file> <output file> <ollama port>");
            System.exit(1);
        }

        String inputFileName = args[0];
        String outputFileName = args[1];

        // connect to Ollama
        String host = "http://localhost:" + args[2] + "/";
        System.out.println("Connecting to " + host);
        OllamaAPI ollamaAPI = new OllamaAPI(host);
        ollamaAPI.setVerbose(false);
        options = new OptionsBuilder().setTemperature(1.0f).build();

        try (BufferedReader br = new BufferedReader(new FileReader(inputFileName));
             BufferedWriter bw = new BufferedWriter(new FileWriter(outputFileName))) {

            String line;
            while ((line = br.readLine()) != null) {
                String prompt = "Just the response. The following sentence was generated by a computer and is worded awkwardly. "
                        + "Maintain meaning, but minimally rephrase the sentence to sound more natural. "
                        + "Place the response in {}. Here is the sentence: "
                        + line;
                System.out.println("Prompt: " + prompt);
                OllamaResult result =
                        ollamaAPI.generate("llama3.2", prompt, RAW_PROMPT, options);

                String response = result.getResponse();
                int start = response.indexOf('{');
                int end = response.indexOf('}');
                System.out.println("Response: " + response);
                if (start != -1 && end != -1 && start < end) {
                    response = response.substring(start + 1, end);
                    bw.write(response);
                } else {
                    bw.write(line);
                }
                bw.newLine();
            }
        }
        catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("Rephrasing complete");
    }
}