# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
name: Java CI with Ant

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build-test-upload:
    name: Built, Test & Upload
    runs-on: ubuntu-latest
    env:
      CATALINA_HOME: ${{ github.workspace }}/tomcat

    steps:
      - name: checkout sigmanlp
        uses: actions/checkout@v4
        with:
          path: sigmanlp

      - name: checkout sigmaAntlr
        uses: actions/checkout@v4
        with:
          repository: 'ontologyportal/sigmaAntlr'
          path: sigmaAntlr

      - name: checkout sigmakee
        uses: actions/checkout@v4
        with:
          repository: 'ontologyportal/sigmakee'
          path: sigmakee

      - name: checkout TPTP-ANTLR
        uses: actions/checkout@v4
        with:
          repository: 'ontologyportal/TPTP-ANTLR'
          path: TPTP-ANTLR

      - name: checkout SigmaUtils
        uses: actions/checkout@v4
        with:
          repository: 'ontologyportal/SigmaUtils'
          path: SigmaUtils

      - name: checkout sumo
        uses: actions/checkout@v4
        with:
          repository: 'ontologyportal/sumo'
          path: sumo

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
#        if: failure() && github.event_name == 'workflow_dispatch'
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3

      - name: Setup SigmaNLP
        env:
          ONTOLOGYPORTAL_GIT: ${{ github.workspace }}
          SIGMA_HOME: ${{ github.workspace }}/sigmakee-runtime
          SIGMA_SRC: ${{ github.workspace }}/sigmakee
          CORPORA: ${{ github.workspace }}/sigmanlp/corpora
        working-directory: ${{ github.workspace }}
        run: |
          echo "SIGMA_HOME: $SIGMA_HOME"
          echo "SIGMA_SRC: $SIGMA_SRC"
          echo "ONTOLOGYPORTAL_GIT: $ONTOLOGYPORTAL_GIT"
          echo "CORPORA: $CORPORA"
          mkdir -p $SIGMA_HOME/KBs/WordNetMappings
          wget -q https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.107/bin/apache-tomcat-9.0.107.tar.gz
          tar -xzf apache-tomcat-9.0.107.tar.gz
          mv apache-tomcat-9.0.107 $CATALINA_HOME
          cp "$SIGMA_SRC/scripts/installation/config.xml" "$SIGMA_HOME/KBs/config.xml"
          cp -R $ONTOLOGYPORTAL_GIT/sumo/* $SIGMA_HOME/KBs
          wget 'https://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz'
          tar -xvzf WordNet-3.0.tar.gz
          cp WordNet-3.0/dict/* $SIGMA_HOME/KBs/WordNetMappings/

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build dependency repositories
        env:
          ONTOLOGYPORTAL_GIT: ${{ github.workspace }}
          SIGMA_HOME: ${{ github.workspace }}/sigmakee-runtime
          SIGMA_SRC: ${{ github.workspace }}/sigmakee
          CORPORA: ${{ github.workspace }}/sigmanlp/corpora
        working-directory: ${{ github.workspace }}
        run: |
          echo "Building SigmaUtils"
          cd "$GITHUB_WORKSPACE/SigmaUtils"
          ant

          echo "Building TPTP-ANTLR"
          cd "$GITHUB_WORKSPACE/TPTP-ANTLR"
          ant

          echo "Building sigmaAntlr"
          cd "$GITHUB_WORKSPACE/sigmaAntlr"
          ant

          echo "Building sigmakee"
          cd "$GITHUB_WORKSPACE/sigmakee"
          ant

      - name: Build with Ant
        env:
          ONTOLOGYPORTAL_GIT: ${{ github.workspace }}
          SIGMA_HOME: ${{ github.workspace }}/sigmakee-runtime
          SIGMA_SRC: ${{ github.workspace }}/sigmakee
          CORPORA: ${{ github.workspace }}/sigmanlp/corpora
        run: ant
        working-directory: ./sigmanlp

      - name: Run unit tests
        env:
          ONTOLOGYPORTAL_GIT: ${{ github.workspace }}
          SIGMA_HOME: ${{ github.workspace }}/sigmakee-runtime
          SIGMA_SRC: ${{ github.workspace }}/sigmakee
          CORPORA: ${{ github.workspace }}/sigmanlp/corpora
        working-directory: ./sigmanlp
        run: ant test.unit

      - name: Prepare integration runtime
        env:
          SIGMA_HOME: ${{ github.workspace }}/sigmakee-runtime
        working-directory: ${{ github.workspace }}
        run: |
          find "$SIGMA_HOME/KBs" -name '*.ser' -delete
          mkdir -p "$SIGMA_HOME/KBs/tests"
          mkdir -p "$SIGMA_HOME/cache"

      - name: Run integration tests
        env:
          ONTOLOGYPORTAL_GIT: ${{ github.workspace }}
          SIGMA_HOME: ${{ github.workspace }}/sigmakee-runtime
          SIGMA_SRC: ${{ github.workspace }}/sigmakee
          CORPORA: ${{ github.workspace }}/sigmanlp/corpora
        working-directory: ./sigmanlp
        run: |
          ant test.integration

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./sigmanlp/build/test/results/*
