name: 'Test Report'

run-name: 'Test Report for ${{ github.event.workflow_run.head_branch }} @ ${{ github.event.workflow_run.head_sha }}'

on:
  workflow_run:
    workflows: ['Java CI with Ant']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    name: Report ${{ gitThub.event.workflow_run.head_branch }}
    runs-on: ubuntu-latest

    steps:
      - name: Show triggering workflow info
        run: |
          echo "Triggered workflow name: ${{ github.event.workflow_run.name }}"
          echo "Triggered workflow id:   ${{ github.event.workflow_run.id }}"
          echo "Triggered branch:        ${{ github.event.workflow_run.head_branch }}"
          echo "Triggered sha:           ${{ github.event.workflow_run.head_sha }}"
          echo "Triggered conclusion:    ${{ github.event.workflow_run.conclusion }}"
          echo "Triggered event:         ${{ github.event.workflow_run.event }}"

      - uses: dorny/test-reporter@v3
        with:
          artifact: test-results
          name: Java Tests - ${{ github.event.workflow_run.head_branch }}
          path: '**/TEST-*.xml'
          reporter: java-junit
          fail-on-error: true